algoritmo "Exercicio 78 Laço Repita"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Rafael Bomfim]
// Descrição   : 78 -  Crie um programa usando o "Repita" que imprima os números de 1 a 50 em ordem decrescente.
// Autor(a)    : Leonardo Alves
// Data atual  : 25/11/2024
var

counter: inteiro

inicio

counter <- 50
repita
    escreval(counter)
    counter <- counter - 1
ate counter = 0

fimalgoritmo