algoritmo "Exercicio 66"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Rafael Bomfim
// Descrição   : 66 -  Crie um programa usando o "PARA" que imprima os números entre 1 e 50 que são múltiplos de 2 e 3.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/11/2024
var

counter: inteiro

inicio

para counter de 1 ate 50 faca
    se (counter % 2 = 0) e (counter % 3 = 0) entao
        escreval (counter)
    fimse
fimpara

fimalgoritmo