algoritmo "Exercio27"
// Função : 27 - Escreva um algoritmo que receba dois números inteiros e determine se eles são iguais ou diferentes.
// Autor : Leonardo
// Data : 14/10/2024
// Seção de Declarações
var

numero1, numero2 : inteiro

inicio
// Seção de Comandos

escreval ("Digite 2 numeros inteiros e direi se são iguais ou diferentes:")
leia(numero1)
leia(numero2)

se numero1 = numero2 entao
   escreval("São iguais")
senao
   escreval("São diferentes")
fimse

fimalgoritmo
