algoritmo "Exercicio 62 Laço Para"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Rafael Bomfim
// Descrição   : 62 -  Crie um programa usando o "PARA" que mostre a tabuada da multiplicação de 7.
// Autor(a)    : Leonardo Alves
// Data atual  : 17/11/2024
var

tabuada: inteiro

inicio

para tabuada de 1 ate 10 faca
    escreval (tabuada, " X 7 = ", tabuada * 7)
fimpara

fimalgoritmo