algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : 70 -  Crie um programa usando o "Repita" que imprima na tela os números de 1 a 10.
// Autor(a)    : Leonardo
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

counter: inteiro

inicio

counter <- 1
repita
    escreval (counter)
    counter <- counter + 1
ate counter > 10

fimalgoritmo