Algoritmo "Exercicio2TESTELacoPARA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Leonardo
// Data atual  : 04/11/2024
Var
   // Seção de Declarações das variáveis
   contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   para contador de 10 ate 50 passo 5 faca
      escreva (contador)
   fimpara

Fimalgoritmo