algoritmo "Exercício 8"
// Função :  Exercício 8 - Faça um algoritmo que receba 2 caracteres, e informe que "Os dois Instrutores de lógica de programação são:" Hermínio e Rafael.
// Autor : Leonardo
// Data : 04/10/2024
// Seção de Declarações 
var
    prof1, prof2 : caractere
inicio
// Seção de Comandos 

prof1 <- "Herminio "
prof2 <- "Rafael "

escreval ("Os dois Instrutores de lógica de programação são: ", prof1 + "e " + prof2)

fimalgoritmo
