algoritmo "Exercicio59"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : 59 -  Crie um programa usando o "PARA" que mostre a contagem dos números múltiplos de 3 de 1 a 30.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

counter: inteiro

inicio

para counter de 3 ate 30 passo 3 faca
    escreval (counter)
fimpara

fimalgoritmo