algoritmo "Soma de 3 Numeros"
// Função :  Exercício 6 - Crie um Algoritmo que calcule e exiba a soma dos primeiros 3 números.
// Autor :  Leonardo
// Data : 04/10/2024
// Seção de Declarações
var
num1, num2, num3, soma: real

inicio
// Seção de Comandos

escreval ("Digite seu primeiro número:")
leia(num1)
escreval ("Digite seu segundo número:")
leia(num2)
escreval ("Digite seu terceiro número:")
leia(num3)
soma <- num1 + num2 + num3
escreval("A soma dos 3 números é: ", soma)



fimalgoritmo
